services:
  nginx:
    container_name: mm-skeleton-nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on:
      - php-fpm
    ports:
      - "8181:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - skeleton-network

  php-fpm:
    container_name: mm-skeleton-backend
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - skeleton-network

  db:
    container_name: mm-skeleton-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - skeleton-network

  swagger:
    container_name: mm-skeleton-swagger
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8029:8080
    links:
      - php-fpm
    environment:
      SWAGGER_JSON: /spec/swagger.yml
    volumes:
      - ./doc/swagger:/spec
    networks:
      - skeleton-network

  rabbitmq:
    container_name: mm-skeleton-rabbit
    build: ./docker/rabbitmq
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    hostname: mm-skeleton-rabbitmq
    volumes:
      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq
    depends_on:
      - php-fpm
    networks:
      - skeleton-network

networks:
  skeleton-network:
    driver: bridge

volumes:
  postgres:
